### PR TITLE
Removing redundant 'myDid' from authcryptable entities 

### PR DESCRIPTION
**Pull request by pimotte**
I came across this while implementing #15, and this would simplify that issue as well.
Removing myDid simplifies the API. If needed, public calls for fine-grained did management can be added at some point.

### CODE REVIEW

**Comment by PJUllrich** [comment]
But is there still a way to get myDid for a connection after you remove this?

**Comment by pimotte** [comment]
https://github.com/Quintor/StudyBits/pull/21/files#diff-3cc4c7a96df4b169a3c7f88a3a94de97L69 allows us to get our own DID given the DID of the partner (which is the logical way to use the Pairwise API, as the Pairwise.getPairwise call requires their DID, not our own. Would you like me to already make this a public method?

**Comment by PJUllrich** [comment]
Yes please. Then I'll merge this.

**Comment by pimotte** [comment]
Done:)

**Pull request merged**
